### ISSUE TITLE
movement of KUKA robot

### ISSUE THREAD

**Issue by Klinggaard** [Klinggaard/RABWDMCP#20]
It is required that we gain knowledge revolving the KUKA robot and how it is operated. This knowledge we will use to make a test movement of the robot.

**THE ROBOT JUST NEEDS TO MOVE IN A CONTROLLED MANOR FOR THIS ISSUE TO BE COMPLETED**

**Comment by Benjaminhvenegaard** [comment]
Tutorial for setup of a KUKA with ROS : https://github.com/ros-industrial/kuka_experimental/tree/indigo-devel/kuka_rsi_hw_interface/krl/KR_C4
